# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([24,89,38,10,89])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))


[10 24 38 89 89]


# Problem 2

In [25]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.arange(5,15)
print(sayilar2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3 = np.arange(50,100,5)
print(sayilar3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4 = np.zeros(10)
print(sayilar4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5 = np.ones(10)
print(sayilar5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6 = np.linspace(0,100,5)
print(sayilar6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
rastgeleSayilar = np.random.randint(10,31,size=5)
print(rastgeleSayilar)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
rastgeleSayilar2 = np.random.uniform(-1,1,size=10)
print(rastgeleSayilar2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
rastgeleSayilar3 = np.random.randint(10,50,size=(3,5))
print(rastgeleSayilar3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(rastgeleSayilar3.sum(axis=0))
print(rastgeleSayilar3.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(rastgeleSayilar3.max())
print(rastgeleSayilar3.min())
print(rastgeleSayilar3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(rastgeleSayilar3.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
rastgeleSayilar4 = np.random.randint(10,20,size=8)
print(rastgeleSayilar4[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(rastgeleSayilar4[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(rastgeleSayilar3[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(rastgeleSayilar3[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(rastgeleSayilar3[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(rastgeleSayilar3**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
rastgeleSayilar5 = np.random.randint(-50,50,size=[3,5])
print((rastgeleSayilar5>0) & (rastgeleSayilar5%2==0))


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[22 13 15 18 18]
[ 0.41137114 -0.04554789 -0.95796645 -0.82620937  0.10911458 -0.08408154
 -0.34751454  0.95220431  0.47440197  0.62372272]
[[16 17 42 47 11]
 [10 16 14 22 47]
 [44 26 27 40 24]]
[ 70  59  83 109  82]
[133 109 161]
47
10
26.866666666666667
3
[11 16 19]
[10 19 10 16 19 19 16 11]
[16 17 42 47 11]
14
[16 10 44]
[[ 256  289 1764 2209  121]
 [ 100  256  196  484 2209]
 [1936  676  729 1600  576]]
[[ True  True False  True False]
 [False False False False False]
 [False False  True False  True]]
