# Problem 1

In [3]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 9.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# 1 - numpy kütüphanesini import edin
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
# 3 - matris'in boyutunu öğrenin
# 4 - matris'i yeniden boyutlandırın
# 5 - matris'in boyut sayısını öğrenin

import numpy as np

matris = np.random.randint(0, 11, size=(5))
boyut = matris.shape
yeniden_boyutlanmis_matris = matris.reshape(5, 1)
boyut_sayisi = matris.ndim

print("Matris: ", matris)
print("Matris Boyutu: ", boyut)
print("Yeniden Boyutlanmiş Matris: \n", yeniden_boyutlanmis_matris)
print("Matris Boyut Sayisi: ", boyut_sayisi)


Matris:  [6 3 8 3 0]
Matris Boyutu:  (5,)
Yeniden Boyutlanmiş Matris: 
 [[6]
 [3]
 [8]
 [3]
 [0]]
Matris Boyut Sayisi:  1


# Problem 2

In [13]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
# 2 - Oluşturduğunuz matrisi parçalayın
# 3 - Parçalanmış matrisleri birleştirin

import numpy as np

matrix = np.arange(1, 10, 2).reshape(5, -1)
print("Oluşturulan matris:\n", matrix)

pieces = np.split(matrix, [2, 3], axis=0)
print("Parçalanan matrisler:\n", pieces)

merged_matrix = np.concatenate(pieces, axis=0)
print("Birleştirilmiş matris:\n", merged_matrix)


Oluşturulan matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]
Parçalanan matrisler:
 [array([[1],
       [3]]), array([[5]]), array([[7],
       [9]])]
Birleştirilmiş matris:
 [[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [7]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
# 2 - matris'in özelliklerini inceleyin

import numpy as np

matrix = np.arange(5, 101, 2)
np.random.shuffle(matrix)
matrix = matrix[:10].reshape(5,2)
print(matrix)

print("Shape: ", matrix.shape)
print("Dimension: ", matrix.ndim)
print("Data Type: ", matrix.dtype)
print("Size: ", matrix.size)
print("Max Value: ", matrix.max())
print("Min Value: ", matrix.min())
print("Mean Value: ", matrix.mean())


[[43 83]
 [21 77]
 [49 13]
 [61 37]
 [29 79]]
Shape:  (5, 2)
Dimension:  2
Data Type:  int32
Size:  10
Max Value:  83
Min Value:  13
Mean Value:  49.2
